/**
 * Site PWA — توليد manifest.json + service-worker.js + webby-config.json
 * لكل موقع مُصدَّر.
 */

export function buildSiteManifest(project, { safeName, siteUrl }) {
  const meta = project.meta || {};
  const name = meta.name || 'My Website';
  const shortName = (name.split(/\s+/)[0] || 'Site').slice(0, 12);
  const description = meta.description || 'موقع شخصي مبني بـ Webby';
  const themeColor = '#4f9dff';

  return JSON.stringify(
    {
      name,
      short_name: shortName,
      description,
      start_url: './index.html',
      scope: './',
      display: 'standalone',
      orientation: 'any',
      background_color: '#121212',
      theme_color: themeColor,
      lang: meta.language || 'ar',
      dir: meta.direction || 'rtl',
      icons: [
        {
          src: 'assets/icon-192.png',
          sizes: '192x192',
          type: 'image/png',
          purpose: 'any maskable'
        },
        {
          src: 'assets/icon-512.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'any maskable'
        }
      ],
      categories: ['portfolio', 'personal'],
      webby: {
        version: 1,
        site_url: siteUrl || '',
        owner: meta.username || meta.name || '',
        builder_path: './webby/index.html'
      }
    },
    null,
    2
  );
}

export function buildSiteServiceWorker(pageFiles) {
  // pageFiles: ['index.html', 'about.html', ...]
  const precacheList = [
    './',
    ...pageFiles.map((p) => `./${p}`),
    './style.css',
    './script.js',
    './manifest.json',
    './webby-config.json',
    './assets/icon-192.png',
    './assets/icon-512.png'
  ];

  return `/* Auto-generated by Webby */
const CACHE_NAME = 'site-v1';
const PRECACHE = ${JSON.stringify(precacheList, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME)
      .then((cache) => cache.addAll(PRECACHE).catch(() => {}))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys.filter((k) => k !== CACHE_NAME).map((k) => caches.delete(k))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET') return;
  if (url.protocol === 'blob:' || url.protocol === 'data:') return;
  if (url.origin !== self.location.origin) return;

  event.respondWith(
    caches.match(event.request).then((cached) => {
      if (cached) return cached;
      return fetch(event.request).then((res) => {
        if (res.ok && res.type === 'basic') {
          const clone = res.clone();
          caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
        }
        return res;
      });
    })
  );
});

self.addEventListener('message', (e) => {
  if (e.data === 'SKIP_WAITING') self.skipWaiting();
});
`;
}

export function buildWebbyConfig(project) {
  const meta = project.meta || {};
  return JSON.stringify(
    {
      version: 1,
      site_url: meta.link || '',
      owner: meta.username || meta.name || '',
      owner_display: meta.name || '',
      bundle: {
        websites: [],
        apis: [],
        rss: []
      },
      generated_at: new Date().toISOString()
    },
    null,
    2
  );
}

/**
 * قائمة ملفات Webby التي ستُنسخ إلى /webby/ في كل موقع مُصدَّر.
 */
export const WEBBY_FILES = [
  'index.html',
  'style.css',
  'manifest.json',
  'src/main.js',

  // core
  'src/core/schema.js',
  'src/core/project.js',
  'src/core/sections.js',
  'src/core/templates.js',
  'src/core/media.js',
  'src/core/feed.js',
  'src/core/project-serializer.js',
  'src/core/user-data.js',

  // editor
  'src/editor/content-editor.js',
  'src/editor/media-manager.js',
  'src/editor/settings-editor.js',
  'src/editor/network-editor.js',

  // exporter
  'src/exporter/html-exporter.js',
  'src/exporter/zip-exporter.js',
  'src/exporter/site-pwa.js',

  // fs
  'src/fs/project-io.js',
  'src/fs/file-system-access.js',
  'src/fs/handle-store.js',
  'src/fs/sync.js',

  // preview
  'src/preview/preview.js',
  'src/preview/vfs.js',

  // renderer
  'src/renderer/page-renderer.js',
  'src/renderer/section-renderer.js',
  'src/renderer/site-renderer.js',
  'src/renderer/site-script.js',

  // ui
  'src/ui/app.js',
  'src/ui/dialogs.js',
  'src/ui/icons.js',
  'src/ui/progress.js',
  'src/ui/pwa.js',

  // utils
  'src/utils/id.js',
  'src/utils/slug.js',

  // web
  'src/web/web.css',
  'src/web/core/content-item.js',
  'src/web/core/connector.js',
  'src/web/core/registry.js',
  'src/web/connectors/openverse.js',
  'src/web/connectors/wikimedia.js',
  'src/web/connectors/internet-archive.js',
  'src/web/ui/cards.js',
  'src/web/ui/search-history.js',
  'src/web/ui/search-view.js',
  'src/web/ui/video-modal.js',
  'src/web/ui/view.js'
];

/**
 * يجلب ملفات Webby من نفس الدومين ويُعيد Map<path, text|blob>.
 */
export async function fetchWebbyFiles(onProgress) {
  const files = new Map();
  const total = WEBBY_FILES.length;

  for (let i = 0; i < WEBBY_FILES.length; i++) {
    const path = WEBBY_FILES[i];
    try {
      const res = await fetch(path, { cache: 'no-store' });
      if (!res.ok) {
        console.warn('[Webby] failed to fetch:', path, res.status);
        continue;
      }
      const text = await res.text();
      files.set(path, text);
    } catch (err) {
      console.warn('[Webby] fetch error:', path, err);
    }
    if (onProgress) onProgress(i + 1, total);
  }

  // أيقونات PWA
  const iconPaths = ['public/icons/icon-192.png', 'public/icons/icon-512.png'];
  for (const iconPath of iconPaths) {
    try {
      const res = await fetch(iconPath, { cache: 'no-store' });
      if (!res.ok) continue;
      const blob = await res.blob();
      const name = iconPath.split('/').pop();
      files.set(`__icon__${name}`, blob);
    } catch (err) {
      console.warn('[Webby] icon fetch error:', err);
    }
  }

  return files;
}

/**
 * يزيل أي حقن من Live Server (script + تعليقات) من نص HTML/JS.
 */
export function stripLiveServerInjection(text) {
  if (!text) return text;

  let out = String(text);

  // 1) احذف سكربت Live Server (بين <!-- Code injected by live-server --> وما بعده)
  out = out.replace(
    /<!--\s*Code injected by live-server\s*-->[\s\S]*?<\/script>/gi,
    ''
  );

  // 2) احذف أي mention لـ live-server ws
  out = out.replace(/\/ws['"`]?\s*\)/gi, "''");
  out = out.replace(/wss?:\/\/[^'"`]*\/ws/gi, '');

  // 3) احذف div#highlighter--hover-tools (من إضافة)
  out = out.replace(
    /<div id="highlighter--hover-tools"[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/gi,
    ''
  );

  // 4) احذف أي script يشير إلى webextension.js (إضافة متصفح)
  out = out.replace(
    /<script[^>]*src="[^"]*webextension[^"]*"[^>]*><\/script>/gi,
    ''
  );

  return out;
}